# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20180522_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='listed', to='wishlist.User'),
        ),
    ]
